### ISSUE TITLE
Doesn't work with Perl 5.22? 

### ISSUE THREAD

**Issue by apredeus** [carden24/V-Xtractor#1]
Hello, 

I was trying to use the tool, and it doesn't seem to pass the test. I've got HMMER  3.1b2 and Perl 5.22. Running the test sequences produces the following errors (and an empty output file): 

> Argument "les,HMMs" isn't numeric in addition (+) at vxtractor.pl line 489, <IN> chunk 1.
> Argument "tedHMMER" isn't numeric in addition (+) at vxtractor.pl line 489, <IN> chunk 1.
> substr outside of string at vxtractor.pl line 500, <IN> chunk 1.
> Use of uninitialized value $values in pattern match (m//) at vxtractor.pl line 501, <IN> chunk 1.
> Argument "les,HMMs" isn't numeric in addition (+) at vxtractor.pl line 489, <IN> chunk 1.
> Argument "tedHMMER" isn't numeric in addition (+) at vxtractor.pl line 489, <IN> chunk 1.
> substr outside of string at vxtractor.pl line 500, <IN> chunk 1.

Another question I had is how do I generate (and is there a need to) generate the HMMs for animals and/or plants if I would want to run it on the corresponding 18S? 

Thank you in advance!

**Comment by carden24** [comment]
Hi Alex,
We current offer no support as it is a very old tool.
I tried it with Perl v5.18.2 and HMMER 3.1b2 and it worked, if you want to try that it might also work for you. 

If you want to make you own HMMs you need to first align the sequences, curate the alignment and then run hmmbuild on the sequences. This is non-trivial as the quality of the model with depend on the sequences you choose. It might be a good idea to see if other researchers have developed HMMs for 18S.

Cheers, 

Erick

**Comment by zkstewart** [comment]
Hi,

Although this program is not being maintained any longer, I thought I'd mention that I also encountered the same problem. I am using the version of Perl suggested (typing perl --version produces the below text)

```
This is perl 5, version 18, subversion 2 (v5.18.2) built for x86_64-linux-thread-multi
```

as well as HMMER 3.1b2 (typing hmmscan -h produces this)

```
# hmmscan :: search sequence(s) against a profile database
# HMMER 3.1b2 (February 2015); http://hmmer.org/
# Copyright (C) 2015 Howard Hughes Medical Institute.
# Freely distributed under the GNU General Public License (GPLv3).
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
```

I attempted to use the following command

```
perl /home/stewarz3/various_programs/V-Xtractor/vxtractor.pl -a -c csvtest.csv -o fastatest.fasta -r .V1-V3. -h /home/stewarz3/various_programs/V-Xtractor/HMMs/bacteria/ /home/stewarz3/various_programs/V-Xtractor/testfile.fasta
```

and received the below error

```
V-Xtractor v. 2.0. Copyright (c) Hartmann et al. 2010.

Argument "les,/hom" isn't numeric in addition (+) at /home/stewarz3/various_programs/V-Xtractor/vxtractor.pl line 489, <IN> chunk 1.
Argument "tedHMMER" isn't numeric in addition (+) at /home/stewarz3/various_programs/V-Xtractor/vxtractor.pl line 489, <IN> chunk 1.
Argument "les,/hom" isn't numeric in addition (+) at /home/stewarz3/various_programs/V-Xtractor/vxtractor.pl line 489, <IN> chunk 1.
Argument "tedHMMER" isn't numeric in addition (+) at /home/stewarz3/various_programs/V-Xtractor/vxtractor.pl line 489, <IN> chunk 1.
Argument "les,/hom" isn't numeric in addition (+) at /home/stewarz3/various_programs/V-Xtractor/vxtractor.pl line 489, <IN> chunk 1.
```

This goes on for 100 "chunks", occasionally interspersed with lines that look like this

```
11:29:43 [============================= ] 98.9% 11:29:48  Remaining: 0:00:00Argument "les,/hom" isn't numeric in addition (+) at /home/stewarz3/various_programs/V-Xtractor/vxtractor.pl line 489, <IN> chunk 99.
Argument "tedHMMER" isn't numeric in addition (+) at /home/stewarz3/various_programs/V-Xtractor/vxtractor.pl line 489, <IN> chunk 99.
Argument "les,/hom" isn't numeric in addition (+) at /home/stewarz3/various_programs/V-Xtractor/vxtractor.pl line 489, <IN> chunk 99.
Argument "tedHMMER" isn't numeric in addition (+) at /home/stewarz3/various_programs/V-Xtractor/vxtractor.pl line 489, <IN> chunk 99.
Argument "les,/hom" isn't numeric in addition (+) at /home/stewarz3/various_programs/V-Xtractor/vxtractor.pl line 489, <IN> chunk 99.
Argument "tedHMMER" isn't numeric in addition (+) at /home/stewarz3/various_programs/V-Xtractor/vxtractor.pl line 489, <IN> chunk 99.
Argument "les,/hom" isn't numeric in addition (+) at /home/stewarz3/various_programs/V-Xtractor/vxtractor.pl line 489, <IN> chunk 99.
Argument "tedHMMER" isn't numeric in addition (+) at /home/stewarz3/various_programs/V-Xtractor/vxtractor.pl line 489, <IN> chunk 99.
Argument "les,/hom" isn't numeric in addition (+) at /home/stewarz3/various_programs/V-Xtractor/vxtractor.pl line 489, <IN> chunk 99.
Argument "tedHMMER" isn't numeric in addition (+) at /home/stewarz3/various_programs/V-Xtractor/vxtractor.pl line 489, <IN> chunk 99.
Argument "les,/hom" isn't numeric in addition (+) at /home/stewarz3/various_programs/V-Xtractor/vxtractor.pl line 489, <IN> chunk 99.
Argument "tedHMMER" isn't numeric in addition (+) at /home/stewarz3/various_programs/V-Xtractor/vxtractor.pl line 489, <IN> chunk 99.
Argument "les,/hom" isn't numeric in addition (+) at /home/stewarz3/various_programs/V-Xtractor/vxtractor.pl line 489, <IN> chunk 99.
Argument "tedHMMER" isn't numeric in addition (+) at /home/stewarz3/various_programs/V-Xtractor/vxtractor.pl line 489, <IN> chunk 99.
Argument "les,/hom" isn't numeric in addition (+) at /home/stewarz3/various_programs/V-Xtractor/vxtractor.pl line 489, <IN> chunk 99.
Argument "tedHMMER" isn't numeric in addition (+) at /home/stewarz3/various_programs/V-Xtractor/vxtractor.pl line 489, <IN> chunk 99.
11:29:43 [==============================]  100% 11:29:48      Total: 0:00:05
Argument "les,/hom" isn't numeric in addition (+) at /home/stewarz3/various_programs/V-Xtractor/vxtractor.pl line 489, <IN> chunk 100.
```

This was all done with the version of V-Xtractor downloaded when running "git clone https://github.com/carden24/V-Xtractor.git". When I used the version downloaded from http://www.microbiome.ch/software, however, I discovered that the HMMs folder was different. When referring to the HMM folder provided in this installation, I can run the vxtractor.pl file regardless of whether this .pl file was downloaded from github or the website, and it also works with Perl version 5.22.0. This should be a solution to the original problem.

**Comment by carden24** [comment]
Thanks for your help Zachary. I will try to fix the problem here and add a link to Martin Hartmann's webpage where the software is also hosted. He developed this software while he was in the Mohn's lab.

Erick
