### ISSUE TITLE
hmmscan v3.1b1 is not working

### ISSUE THREAD

**Issue by hildebra** [carden24/V-Xtractor#3]
Hey, I wanted to use V-Xtractor, but I cant get it to work with the provided HMMs.zip archieve. 
Using HMMER 3.1b1 (May 2013) I get the following error:
 hmmscan --cpu 2 --max --domE 1E-04 /hpc-home/hildebra/vxtr/HMMs//bacteria//V1leftlong.HMM temp.pid.14030            
Error: bad format, binary auxfiles, /hpc-home/hildebra/vxtr/HMMs//bacteria//V1leftlong.HMM:
binary auxfiles are in an outdated HMMER format (3/b); please hmmpress your HMM file again
Is this an expected error?
I also added some options like setting CPU cores etc, let me know if there's an interest to merge these into the project.
thanks, Falk

**Comment by carden24** [comment]
I think it is expected given the differences in hmmer. I an not the owner of this project, you can contact Martin Hartmann which is the original coder at http://www.microbiome.ch/software
